#!/bin/sh

## vracker's collections: open-source
## GNU Screen
##
## Copyright (C) 2016 Przemyslaw Pawelczyk <przemoc@gmail.com>
##
## This script is licensed under the terms of the MIT license.
## https://opensource.org/licenses/MIT

export NEWSFILE=src/ChangeLog
exec vracker-template-gnu screen 'v.$VER'
