#!/bin/sh

## vracker's collections: open-source
## Expect
##
## Copyright (C) 2016 Przemyslaw Pawelczyk <przemoc@gmail.com>
##
## This script is licensed under the terms of the MIT license.
## https://opensource.org/licenses/MIT

NAME=expect
NAME_U="$(echo "$NAME" | sed 's,.,\u&,')"
URL="https://sourceforge.net/projects/$NAME/files/$NAME_U/"
CONTENT="$(\
	vracker-download \
		--xform '/<!-- Server: .* -->/d' \
		--xform '/<meta charset[^>]*>/d' \
		--xform '/<style.*\/style>/d' \
		--xform '/<style[^>]*>/,/<\/style>/d' \
		--xform '/<script.*\/script>/d' \
		--xform '/<script[^>]*>/,/<\/script>/d' \
		--xform '/<noscript.*\/noscript>/d' \
		--xform '/<noscript[^>]*>/,/<\/noscript>/d' \
		--xform '/<header[^>]*>/,/<\/header>/d' \
		--xform '/<footer[^>]*>/,/<\/footer>/d' \
		--xform '/<p.*\/p>/d' \
		--xform '/<p[^>]*>/,/<\/p>/d' \
		--xform '/<input/d' \
		--xform '/<textarea/d' \
		--xform '/<td headers="files_downloads_h" class="opt">/{/<\/td>/!N;d;}' \
		--xform 's/?[0-9]*"/"/' \
		"$URL" \
)"
URLPATH="$(echo "$URL" | sed 's,^[^:]*://[^/]*,,')"
VER="$(\
	echo "$CONTENT" \
		| hxnormalize -xi0 -l9999 \
		| hxselect -c 'a[class="name"][href^="'"$URLPATH"'"]' -s '\n' \
		| sed 's,^ *,,;s, *$,,' \
		| sort -rV | sed 1q \
)"
URL="$URL$VER/"
CONTENT="$(\
	vracker-download \
		--xform '/<!-- Server: .* -->/d' \
		--xform '/<meta charset[^>]*>/d' \
		--xform '/<style.*\/style>/d' \
		--xform '/<style[^>]*>/,/<\/style>/d' \
		--xform '/<script.*\/script>/d' \
		--xform '/<script[^>]*>/,/<\/script>/d' \
		--xform '/<noscript.*\/noscript>/d' \
		--xform '/<noscript[^>]*>/,/<\/noscript>/d' \
		--xform '/<header[^>]*>/,/<\/header>/d' \
		--xform '/<footer[^>]*>/,/<\/footer>/d' \
		--xform '/<p.*\/p>/d' \
		--xform '/<p[^>]*>/,/<\/p>/d' \
		--xform '/<input/d' \
		--xform '/<textarea/d' \
		--xform '/<td headers="files_downloads_h" class="opt">/{/<\/td>/!N;d;}' \
		--xform 's/?[0-9]*"/"/' \
		"$URL" \
)"
[ -n "$VRACKER_DOWNLOAD_ONLY" ] && exit

FILE_PLUS_DATE="$(\
	echo "$CONTENT" \
		| hxnormalize -xi0 -l9999 \
		| hxselect 'tr[title^="'$NAME'"]' -s '\n' \
		| sed '/headers="files_\(name\|date\)_h"/!d;s,<[^>]*> *<[^>]*> *,,;s, *<.*,,' \
		| sed 'N;s,\n,: ,' \
		| sort -r | sed 1q \
)"

FILE="${FILE_PLUS_DATE%%:*}"
DATE="$(date -d "${FILE_PLUS_DATE#*: }" +%F)"

echo "{"
	echo "  \"$VER\": {"
	echo "    \"date\": \"$DATE\","
	echo "    \"src\": \"$URL$FILE\""
	echo "  }"
echo "}"
