#!/bin/sh

## vracker's collections: open-source
## git
##
## Copyright (C) 2016 Przemyslaw Pawelczyk <przemoc@gmail.com>
##
## This script is licensed under the terms of the MIT license.
## https://opensource.org/licenses/MIT

NAME=git
URL="https://www.kernel.org/pub/software/scm/$NAME/"
CONTENT="$(vracker-download "$URL")"
[ -n "$VRACKER_DOWNLOAD_ONLY" ] && exit

FILE_PLUS_DATE="$(\
	echo "$CONTENT" \
		| sed \
		  -e  '/^<a href="'"$NAME"'-[0-9]/!d' \
		  -e  '/\.sign/d' \
		  -e  's,^<a href[^>]*>,,;s,</a> *,: ,;s,   *[^ ]* *$,,' \
		| sort -rV | sed 1q
)"

FILE="${FILE_PLUS_DATE%%:*}"
SIGN="${FILE%%.tar*}.tar.sign"
DATE="$(date -d "${FILE_PLUS_DATE#*: }" +%F)"
VER="${FILE#$NAME-}"
VER="${VER%%.tar*}"

CGITURL="https://git.kernel.org/cgit/$NAME/$NAME.git/"
echo "{"
echo "  \"$VER\": {"
echo "    \"date\": \"$DATE\","
echo "    \"src\": \"$URL$FILE\","
echo "    \"src_sign\": \"$URL$SIGN\","
echo "    \"relnotes\": \"${CGITURL}plain/Documentation/RelNotes/$VER.txt\","
echo "    \"changelog\": \"${CGITURL}log/?h=v$VER\""
echo "  }"
echo "}"
