#!/bin/sh

## vracker's collections: non-free
## REAPER
##
## Copyright (C) 2016 Przemyslaw Pawelczyk <przemoc@gmail.com>
##
## This script is licensed under the terms of the MIT license.
## https://opensource.org/licenses/MIT

NAME=reaper
URL="http://reaper.fm/download.php"
CONTENT="$(vracker-download "$URL")"
[ -n "$VRACKER_DOWNLOAD_ONLY" ] && exit

VER_PLUS_DATE="$(\
	echo "$CONTENT" \
		| hxnormalize -xi0 \
		| hxselect -c -s '\n' 'div.hdrbottom' \
		| sed '/^Version /!d;s,,,;q' \
)"
BINARIES="$(\
	echo "$CONTENT" \
		| hxnormalize -xi0 \
		| hxselect -s '\n' 'a[href^=files]' \
		| sed 's,^[^"]*",,;s,".*,,' \
)"
VER="${VER_PLUS_DATE%%:*}"
DATE="$(date -d "${VER_PLUS_DATE#*: }" +%F)"

BASEURL="http://reaper.fm/"
echo "{"
echo "  \"$VER\": {"
echo "    \"date\": \"$DATE\","
echo "    \"bins\": ["
echo "$BINARIES" | sed 's,^,      "'"$BASEURL"',;s,$,",;$!s/$/,/'
echo "    ],"
echo "    \"changelog\": \"${BASEURL}whatsnew.txt\""
echo "  }"
echo "}"
