#!/bin/sh

## vracker's collections: open-source
## GNU Libtool - The GNU Portable Library Tool
##
## Copyright (C) 2016 Przemyslaw Pawelczyk <przemoc@gmail.com>
##
## This script is licensed under the terms of the MIT license.
## https://opensource.org/licenses/MIT

exec vracker-template-gnu libtool
