#!/bin/sh

## vracker's collections: open-source
## util-linux
##
## Copyright (C) 2016 Przemyslaw Pawelczyk <przemoc@gmail.com>
##
## This script is licensed under the terms of the MIT license.
## https://opensource.org/licenses/MIT

NAME=util-linux
URL="https://www.kernel.org/pub/linux/utils/$NAME/"
CONTENT="$(vracker-download "$URL")"
RIDX=${1:-1}
MVER="$(\
	echo "$CONTENT" \
		| sed '/^<a href="v/!d;s,,,;s,/".*,,' \
		| vracker-vsort -r | sed "$RIDX"'!d;q'
)"
URL="${URL}v$MVER/"
CONTENT="$(vracker-download "$URL")"
[ -n "$VRACKER_DOWNLOAD_ONLY" ] && exit

FILES_PLUS_DATES="$(\
	echo "$CONTENT" \
		| sed \
		  -e  '/^<a href="'"$NAME"'-'"$MVER"'/!d' \
		  -e  '/-rc/d' \
		  -e  '/\.sign/d' \
		  -e  's,^<a href[^>]*>,,;s,</a> *,: ,;s,   *[^ ]* *$,,' \
)"

if [ -z "$FILES_PLUS_DATES" ]; then
	exec "$0" $((RIDX + 1))
	exit
fi

FILE_PLUS_DATE="$(\
	echo "$FILES_PLUS_DATES" \
		| grep \
			"^$(echo "$FILES_PLUS_DATES" \
				| sed 's,\.tar.*,,' | vracker-vsort -ru | sed 1q \
			).tar" \
		| sort -r | sed 1q \
)"

FILE="${FILE_PLUS_DATE%%:*}"
SIGN="${FILE%%.tar*}.tar.sign"
DATE="$(date -d "${FILE_PLUS_DATE#*: }" +%F)"
VER="${FILE#$NAME-}"
VER="${VER%%.tar*}"

echo "{"
echo "  \"$VER\": {"
echo "    \"date\": \"$DATE\","
echo "    \"src\": \"$URL/$FILE\","
echo "    \"src_sign\": \"$URL$SIGN\","
echo "    \"relnotes\": \"${URL}v$VER-ReleaseNotes\","
echo "    \"changelog\": \"${URL}v$VER-ChangeLog\""
echo "  }"
echo "}"
