#!/bin/sh

## vracker's collections: open-source
## Tcl
##
## Copyright (C) 2016 Przemyslaw Pawelczyk <przemoc@gmail.com>
##
## This script is licensed under the terms of the MIT license.
## https://opensource.org/licenses/MIT

NAME=tcl
URL="https://www.tcl.tk/software/tcltk/download.html"
CONTENT="$(vracker-download "$URL")"

FILES="$(\
	echo "$CONTENT" \
		| hxnormalize -xi0 -l9999 \
		| hxselect -s '\n' 'a[href$=".tar.gz"]' \
		| sed 's,^[^"]*",,;s,".*$,,;/tcl[0-9]/!d' \
)"
CNT=$(echo "$FILES" | wc -l)
I=0

echo "{"
echo "$FILES" | while read -r FILE; do
	I=$((I+1))
	DATE="$(\
		vracker-download --head --xform '/^\(Date\|ETag\|Connection\|Content-Length\|Content-Type\|Location\|Server\|Set-Cookie\): /d;' "$FILE" \
		| sed '/^Last-Modified: /!d;s,,,')"
	[ -n "$VRACKER_DOWNLOAD_ONLY" ] && continue
	DATE="$(date -d "$DATE" +%F)"
	VER="${FILE##*$NAME}"
	VER="${VER%%-src*}"
	TAG="$(echo "$VER" | sed 's,\.,-,g;s,^,core-,')"
	echo "  \"$VER\": {"
	echo "    \"date\": \"$DATE\","
	echo "    \"src\": \"$FILE\","
	echo "    \"changelog\": \"http://core.tcl.tk/tcl/artifact?filename=changes&ci=$TAG\""
	printf "  }"
	[ $I -lt $CNT ] && printf ","
	echo
done
echo "}"
