#!/bin/sh

## vracker's collections: open-source
## elfutils
##
## Copyright (C) 2016 Przemyslaw Pawelczyk <przemoc@gmail.com>
##
## This script is licensed under the terms of the MIT license.
## https://opensource.org/licenses/MIT

NAME=elfutils
NAMEDIR=$(echo "$NAME" | sed 's,\(.\)\(.\).*,\1/\2,')
URL="https://fedorahosted.org/releases/$NAMEDIR/$NAME/"
CONTENT="$(vracker-download "$URL")"
MVER="$(\
	echo "$CONTENT" \
		| sed \
		  -e  '/^ *<a href="/!d;s,,,' \
		  -e  '/\/".*/!d;s,,,' \
		| sort -rV | sed 1q
)"
URL="$URL$MVER/"
CONTENT="$(vracker-download "$URL")"
[ -n "$VRACKER_DOWNLOAD_ONLY" ] && exit

FILES_PLUS_DATES="$(\
	echo "$CONTENT" \
		| sed \
		  -e  '/ *<a href="'"$NAME"'-[0-9]/!d' \
		  -e  '/\.sig/d' \
		  -e  's,^.*<a href=",,' \
		  -e  's,">[^<]*</a> *,: ,' \
		  -e  's,  .*,,' \
)"

FILE_PLUS_DATE="$(\
	echo "$FILES_PLUS_DATES" \
		| grep \
			"^$(echo "$FILES_PLUS_DATES" \
				| sed 's,\.tar.*,,' | sort -ruV | sed 1q \
			).tar" \
		| sort -r | sed 1q \
)"

FILE="${FILE_PLUS_DATE%%:*}"
SIGN="$FILE.sig"
DATE="$(date -d "${FILE_PLUS_DATE#*: }" +%F)"
VER="${FILE#$NAME-}"
VER="${VER%%.tar*}"
TAG="$NAME-$VER"

CGITURL="https://git.fedorahosted.org/cgit/$NAME.git/"
echo "{"
echo "  \"$VER\": {"
echo "    \"date\": \"$DATE\","
echo "    \"src\": \"$URL$FILE\","
echo "    \"src_sign\": \"$URL$SIGN\","
echo "    \"relnotes\": \"${CGITURL}plain/NEWS?h=$TAG\","
echo "    \"changelog\": \"${CGITURL}log/?h=$TAG\""
echo "  }"
echo "}"
