#!/bin/sh

## vracker's collections: open-source
## GNU Libtasn1
##
## Copyright (C) 2016 Przemyslaw Pawelczyk <przemoc@gmail.com>
##
## This script is licensed under the terms of the MIT license.
## https://opensource.org/licenses/MIT

exec vracker-template-gnu libtasn1 '${NAME}_$(echo "$VER" | sed "s,\\.,_,g")'
