#!/bin/sh

## vracker's collections: open-source
## systemtap
##
## Copyright (C) 2016 Przemyslaw Pawelczyk <przemoc@gmail.com>
##
## This script is licensed under the terms of the MIT license.
## https://opensource.org/licenses/MIT

NAME=systemtap
URL="https://sourceware.org/$NAME/ftp/releases/"
CONTENT="$(vracker-download "$URL")"
[ -n "$VRACKER_DOWNLOAD_ONLY" ] && exit

FILES_PLUS_DATES="$(\
	echo "$CONTENT" \
		| sed \
		  -e  '/<a href="'"$NAME"'-[0-9]/!d' \
		  -e  '/\.\(asc\|sig\)/d' \
		  -e  's,^.*<td><a href=",,' \
		  -e  's,">[^<]*</a></td><td[^>]*>,: ,' \
		  -e  's, *</td>.*,,' \
)"

FILE_PLUS_DATE="$(\
	echo "$FILES_PLUS_DATES" \
		| grep \
			"^$(echo "$FILES_PLUS_DATES" \
				| sed '/\.tar.*/!d;s,,,' | vracker-vsort -ru | sed 1q \
			).tar" \
		| sort -r | sed 1q \
)"

FILE="${FILE_PLUS_DATE%%:*}"
SIGN="$FILE.asc"
DATE="$(vracker-date-to-iso8601 "${FILE_PLUS_DATE#*: }")"
VER="${FILE#$NAME-}"
VER="${VER%%.tar*}"
TAG="release-$VER"

GITWEBURL="https://sourceware.org/git/?p=$NAME.git"
echo "{"
echo "  \"$VER\": {"
echo "    \"date\": \"$DATE\","
echo "    \"src\": \"$URL$FILE\","
echo "    \"src_sign\": \"$URL$SIGN\","
echo "    \"relnotes\": \"$GITWEBURL;a=blob_plain;f=NEWS;hb=refs/tags/$TAG\","
echo "    \"changelog\": \"$GITWEBURL;a=shortlog;h=refs/tags/$TAG\""
echo "  }"
echo "}"
