#!/bin/sh

## vracker's templates: GNU
##
## Copyright (C) 2016 Przemyslaw Pawelczyk <przemoc@gmail.com>
##
## This script is licensed under the terms of the MIT license.
## https://opensource.org/licenses/MIT

if [ $# -eq 0 -o "$1" = "-h" -o "$1" = "--help" ]; then
	echo "Usage: $0 NAME [TAG_TEMPLATE]"
	echo
	echo "Default TAG_TEMPLATE is 'v\$VER'."
	echo
	echo "Examples:"
	echo
	printf "    $0 %s\n"      coreutils
	printf "    $0 %s '%s'\n" dejagnu   '$NAME-$VER-release'
	printf "    $0 %s '%s'\n" tar       'release_$(echo "$VER" | sed "s,\\.,_,g")'
	exit 0
fi

NAME="$1"
URL="http://ftp.gnu.org/gnu/$NAME/"
CONTENT="$(vracker-download "$URL")"
[ -n "$VRACKER_DOWNLOAD_ONLY" ] && exit

FILES_PLUS_DATES="$(\
	echo "$CONTENT" \
		| sed \
		  -e  '/<a href="'"$NAME"'-[0-9]/!d' \
		  -e  '/\.sig/d' \
		  -e  's,^.*<td><a href=",,' \
		  -e  's,">[^<]*</a></td><td[^>]*>,: ,' \
		  -e  's, *</td>.*,,' \
)"

FILE_PLUS_DATE="$(\
	echo "$FILES_PLUS_DATES" \
		| grep \
			"^$(echo "$FILES_PLUS_DATES" \
				| sed '/\.tar.*/!d;s,,,' | sort -ruV | sed 1q \
			).tar" \
		| sort -r | sed 1q \
)"

FILE="${FILE_PLUS_DATE%%:*}"
SIGN="$FILE.sig"
DATE="$(date -d "${FILE_PLUS_DATE#*: }" +%F)"
VER="${FILE#$NAME-}"
VER="${VER%%.tar*}"
TAG="${2:-v\$VER}"

eval "TAG=\"$TAG\""

CGITURL="http://git.savannah.gnu.org/cgit/$NAME.git/"
echo "{"
echo "  \"$VER\": {"
echo "    \"date\": \"$DATE\","
echo "    \"src\": \"$URL$FILE\","
echo "    \"src_sign\": \"$URL$SIGN\","
echo "    \"relnotes\": \"${CGITURL}plain/NEWS?id=$TAG\","
echo "    \"changelog\": \"${CGITURL}log/?id=$TAG\""
echo "  }"
echo "}"
