#!/bin/sh

## vracker's collections: open-source
## musl libc
##
## Copyright (C) 2016 Przemyslaw Pawelczyk <przemoc@gmail.com>
##
## This script is licensed under the terms of the MIT license.
## https://opensource.org/licenses/MIT

NAME=musl
URL="http://www.musl-libc.org/download.html"
CONTENT="$(vracker-download "$URL")"
[ -n "$VRACKER_DOWNLOAD_ONLY" ] && exit

VERSIONS="$(\
	echo "$CONTENT" \
		| hxnormalize -xi0 -l9999 \
		| hxselect -c -s '\n' p \
		| grep '^<a href' \
)"
CNT=$(echo "$VERSIONS" | wc -l)
I=0

BASEURL="http://www.musl-libc.org/"
CGITURL="http://git.musl-libc.org/cgit/$NAME/"
echo "{"
echo "$VERSIONS" | while read -r LINE; do
	I=$((I+1))
	FILE="$(echo "$LINE" | sed 's,^[^"]*",,;s,".*,,')"
	SIGN="$(echo "$LINE" | sed 's,^[^"]*"[^"]*"[^"]*",,;s,".*,,')"
	DATE="$(vracker-date-to-iso8601 "${LINE##* - }")"
	VER="${FILE##*$NAME-}"
	VER="${VER%%.tar*}"
	TAG="v$VER"
	echo "  \"$VER\": {"
	echo "    \"date\": \"$DATE\","
	echo "    \"src\": \"$BASEURL$FILE\","
	echo "    \"src_sign\": \"$BASEURL$SIGN\","
	echo "    \"relnotes\": \"${CGITURL}plain/WHATSNEW?h=$TAG\","
	echo "    \"changelog\": \"${CGITURL}log/?h=$TAG\""
	printf "  }"
	[ $I -lt $CNT ] && printf ","
	echo
done
echo "}"
