#!/bin/sh

## vracker's collections: open-source
## Coreutils - GNU core utilities
##
## Copyright (C) 2016 Przemyslaw Pawelczyk <przemoc@gmail.com>
##
## This script is licensed under the terms of the MIT license.
## https://opensource.org/licenses/MIT

NAME=coreutils
URL="http://ftp.gnu.org/gnu/$NAME/"
CONTENT="$(vracker-download "$URL")"
[ -n "$VRACKER_DOWNLOAD_ONLY" ] && exit

FILE_PLUS_DATE="$(\
	echo "$CONTENT" \
		| sed \
		  -e  '/<a href="'"$NAME"'-[0-9]/!d' \
		  -e  '/\.sig/d' \
		  -e  's,^.*<td><a href=",,' \
		  -e  's,">[^<]*</a></td><td[^>]*>,: ,' \
		  -e  's, *</td>.*,,' \
		| sort -rV | sed 1q
)"

FILE="${FILE_PLUS_DATE%%:*}"
SIGN="$FILE.sig"
DATE="$(date -d "${FILE_PLUS_DATE#*: }" +%F)"
VER="${FILE#$NAME-}"
VER="${VER%%.tar*}"
TAG="$NAME-$(echo "$VER" | sed 's,\.,_,g')"

CGITURL="http://git.savannah.gnu.org/cgit/$NAME.git/"
echo "{"
echo "  \"$VER\": {"
echo "    \"date\": \"$DATE\","
echo "    \"src\": \"$URL$FILE\","
echo "    \"src_sign\": \"$URL$SIGN\","
echo "    \"relnotes\": \"${CGITURL}plain/NEWS?id=v$VER\","
echo "    \"changelog\": \"${CGITURL}log/?id=v$VER\""
echo "  }"
echo "}"
